package com.tripaty.portfolio.tiru

enum class TiruIntent {
    GREETING, EXPERIENCE, PROJECTS, SKILLS, CERTIFICATIONS, CONTACT,
    LEADERSHIP, AI, TESTIMONIALS, AIRLINE, BANKING, ENTERPRISE, RESUME, FALLBACK,
}
